# бот для сотрудников, сюда вставляем токен, полученный в Telegram от BotFather

telegram_token: token_from_BotFather

# ai_provider - это поставщик ИИ. поддерживаются значения sber и yandex. 
# значение sber некоторое время не поддерживается и его скорее всего придется доработать напильником

ai_provider: yandex

# Конфиг для Телеграм

## здесь список разрешенных пользователей телеги, которые могут задавать вопросы ИИ

allowed_users:
  - dmitry_timoshenko
  - 

# Приветственное сообщение
hello_message: >
  Привет! 
                 
  Это бот корпоративного ИИ. Я умею консультировать по корпоративным вопросам. 
                 
  Просто пиши вопросы или давай мне поручения в этом чате, а я буду тебе отвечать.

# Сообщение, которое бот пишет, если пользователь не включен в список allowed_users
refuse_message: Этот бот доступен только сотрудникам компании

# Конфиг для Яндекс

service_account_id: вставь_сюда_свои_данные
api_key_id: вставь_сюда_свои_данные
folder_id: вставь_сюда_свои_данные
service_account_private_key: >
  сюда
  вставить
  полный 
  текст 
  приватного
  ключа
  "как есть"
  включая
  переносы
  строк